apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: og-rummy-api
  namespace: og-rummy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: og-rummy-api
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
