apiVersion: v1
kind: Secret
metadata:
  name: og-rummy-secrets
  namespace: og-rummy
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:mBRlO%5BKq%21z9R5E3%3A.0VNgcc%2A7U8b@og-rummy-db.cu7wcwuo4gcw.us-east-1.rds.amazonaws.com:5432/postgres"
  JWT_SECRET: "yilj65X/27+ct0bNqIcR7Dykud+7AePdaKFrgXxE9DljuP3UUOwtvBtmPteo82DF4dtsZ4DFGeTWSmdXe9F2wA=="
  RAZORPAY_KEY_ID: "CHANGE_ME_RAZORPAY_KEY_ID"
  RAZORPAY_KEY_SECRET: "CHANGE_ME_RAZORPAY_KEY_SECRET"
  