#!/bin/sh
set -eu

APP_DIR="${APP_DIR:-$PWD}"
APP_NAME="${APP_NAME:-og-rummy-api}"
IMAGE_NAME="${IMAGE_NAME:-og-rummy-backend:latest}"
APP_PORT="${APP_PORT:-80}"
CONTAINER_PORT="${CONTAINER_PORT:-3000}"
HEALTHCHECK_URL="${HEALTHCHECK_URL:-http://localhost/health}"
HEALTHCHECK_RETRIES="${HEALTHCHECK_RETRIES:-18}"
HEALTHCHECK_INTERVAL="${HEALTHCHECK_INTERVAL:-5}"

required_vars="DATABASE_URL JWT_SECRET AWS_REGION AWS_S3_BUCKET AWS_S3_BASE_URL"
for var_name in $required_vars; do
  eval "var_value=\${$var_name:-}"
  if [ -z "$var_value" ]; then
    echo "Missing required env var: $var_name" >&2
    exit 1
  fi
done

cd "$APP_DIR"

cat > .env <<EOF
PORT=${PORT:-3000}
NODE_ENV=${NODE_ENV:-production}
KAFKA_BROKERS=${KAFKA_BROKERS:-localhost:9092}
DATABASE_URL=${DATABASE_URL}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
AWS_REGION=${AWS_REGION}
AWS_S3_BUCKET=${AWS_S3_BUCKET}
AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
${REDIS_URL:+REDIS_URL=${REDIS_URL}}

# Bot configuration – aligned with docker-compose.yml
POOL_SPLIT_ENABLED=${POOL_SPLIT_ENABLED:-true}
BOT_ENGINE_ENABLED=${BOT_ENGINE_ENABLED:-true}
ENABLE_BOT_SOFT_RIGGING=${ENABLE_BOT_SOFT_RIGGING:-true}
BOT_INJECT_AFTER_SECONDS=${BOT_INJECT_AFTER_SECONDS:-7}
BOT_SCAN_EVERY_MS=${BOT_SCAN_EVERY_MS:-5000}
BOT_SCAN_BATCH_LIMIT=${BOT_SCAN_BATCH_LIMIT:-25}
BOT_POOL_SIZE=${BOT_POOL_SIZE:-50}
BOT_AUTO_READY=${BOT_AUTO_READY:-true}
BOT_NAME_PREFIX=${BOT_NAME_PREFIX:-RummyBot-}
BOT_PHONE_PREFIX=${BOT_PHONE_PREFIX:-98999}
BOT_SESSION_LOCK_TTL_SECONDS=${BOT_SESSION_LOCK_TTL_SECONDS:-20}
BOT_ACTION_DELAY_MIN_MS=${BOT_ACTION_DELAY_MIN_MS:-800}
BOT_ACTION_DELAY_MAX_MS=${BOT_ACTION_DELAY_MAX_MS:-3200}
BOT_ACTION_DELAY_MS=${BOT_ACTION_DELAY_MS:-0}
BOT_POST_PICK_DELAY_MIN_MS=${BOT_POST_PICK_DELAY_MIN_MS:-2000}
BOT_POST_PICK_DELAY_MAX_MS=${BOT_POST_PICK_DELAY_MAX_MS:-8000}
BOT_POST_PICK_DELAY_MS=${BOT_POST_PICK_DELAY_MS:-0}
BOT_DECLARE_RESPONSE_DELAY_MS=${BOT_DECLARE_RESPONSE_DELAY_MS:-800}
BOT_AGGRESSION_ENABLED=${BOT_AGGRESSION_ENABLED:-true}
BOT_STRATEGIC_DROP_ENABLED=${BOT_STRATEGIC_DROP_ENABLED:-true}
BOT_DROP_BENEFIT_THRESHOLD=${BOT_DROP_BENEFIT_THRESHOLD:-20}
BOT_EARLY_DROP_DEAD_HAND_ENABLED=${BOT_EARLY_DROP_DEAD_HAND_ENABLED:-true}
BOT_HOPELESS_DISPLAY_POINT=${BOT_HOPELESS_DISPLAY_POINT:-45}
BOT_HOPELESS_TURN_MIN=${BOT_HOPELESS_TURN_MIN:-4}
BOT_POOL_COMFORTABLE_HEADROOM=${BOT_POOL_COMFORTABLE_HEADROOM:-45}
BOT_POOL_NEAR_ELIMINATION_HEADROOM=${BOT_POOL_NEAR_ELIMINATION_HEADROOM:-28}
BOT_POOL_HIGH_SCORE_DROP_AT=${BOT_POOL_HIGH_SCORE_DROP_AT:-50}
BOT_SPLIT_AUTO_RESPONSE_MIN_MS=${BOT_SPLIT_AUTO_RESPONSE_MIN_MS:-600}
BOT_SPLIT_AUTO_RESPONSE_MAX_MS=${BOT_SPLIT_AUTO_RESPONSE_MAX_MS:-1500}
BOT_SPLIT_MIN_GAIN_MULTIPLIER=${BOT_SPLIT_MIN_GAIN_MULTIPLIER:-0.6}
MATCH_COUNTDOWN_SECONDS=${MATCH_COUNTDOWN_SECONDS:-10}
MATCH_COUNTDOWN_LOCK_AT_SECONDS=${MATCH_COUNTDOWN_LOCK_AT_SECONDS:-3}

# Reliable-architecture: Redis session-state read cache (Postgres stays source of truth)
SESSION_STATE_CACHE_ENABLED=${SESSION_STATE_CACHE_ENABLED:-true}
SESSION_STATE_CACHE_TTL_MS=${SESSION_STATE_CACHE_TTL_MS:-30000}

# Phase 3 live session state — Redis authoritative; PG snapshot coalesced
LIVE_SESSION_STATE_ENABLED=${LIVE_SESSION_STATE_ENABLED:-true}
LIVE_SESSION_STATE_ASYNC_PG=${LIVE_SESSION_STATE_ASYNC_PG:-true}
LIVE_SESSION_STATE_TTL_MS=${LIVE_SESSION_STATE_TTL_MS:-21600000}
LIVE_SESSION_ASYNC_PG_CONCURRENCY=${LIVE_SESSION_ASYNC_PG_CONCURRENCY:-2}

# Scale foundations — multi-instance safe when Redis is configured
DB_POOL_MAX=${DB_POOL_MAX:-20}
DB_POOL_SPLIT=${DB_POOL_SPLIT:-true}
DB_POOL_MAX_GAMEPLAY=${DB_POOL_MAX_GAMEPLAY:-${DB_POOL_MAX}}
DB_POOL_MAX_AUTH=${DB_POOL_MAX_AUTH:-6}
CLUSTER_INSTANCES=${CLUSTER_INSTANCES:-2}
DURABLE_TIMER_ARM=${DURABLE_TIMER_ARM:-true}
DURABLE_TIMER_SWEEPER_ENABLED=${DURABLE_TIMER_SWEEPER_ENABLED:-true}
DURABLE_TIMER_GRACE_MS=${DURABLE_TIMER_GRACE_MS:-2000}
PROCESS_LEADER_ENABLED=${PROCESS_LEADER_ENABLED:-true}
SOCKET_TRANSPORTS=${SOCKET_TRANSPORTS:-websocket}

# Bot finish-eval hard budgets (prevent gameplay event-loop stalls)
BOT_FINISH_EVAL_BUDGET_MS=${BOT_FINISH_EVAL_BUDGET_MS:-40}
BOT_FINISH_EVAL_MAX_CARDS=${BOT_FINISH_EVAL_MAX_CARDS:-5}
GROUPING_FINISH_SCAN_BUDGET_MS=${GROUPING_FINISH_SCAN_BUDGET_MS:-20}
GROUPING_WORKER_ENABLED=${GROUPING_WORKER_ENABLED:-true}
GROUPING_WORKER_COUNT=${GROUPING_WORKER_COUNT:-2}
PICK_ACK_FINISH_PLAN_MAX_CANDIDATES=${PICK_ACK_FINISH_PLAN_MAX_CANDIDATES:-0}
MAX_SOCKETS_PER_WORKER=${MAX_SOCKETS_PER_WORKER:-500}
ADMIT_MAX_EVENT_LOOP_LAG_MS=${ADMIT_MAX_EVENT_LOOP_LAG_MS:-120}

# GiftAura payment gateway (pay-in)
GIFTAURA_PG_API_URL=${GIFTAURA_PG_API_URL:-https://pgapi.giftaura.shop/paynow}
GIFTAURA_PAYIN_STATUS_API_URL=${GIFTAURA_PAYIN_STATUS_API_URL:-https://pgapi.giftaura.shop/payinstatus}
GIFTAURA_MERCHANT_ID=${GIFTAURA_MERCHANT_ID:-INDIANPAY00GIFTAURA00004}
GIFTAURA_MERCHANT_TOKEN=${GIFTAURA_MERCHANT_TOKEN:-}
GIFTAURA_PG_TYPE=${GIFTAURA_PG_TYPE:-2}
GIFTAURA_REMARK=${GIFTAURA_REMARK:-Add Cash}
GIFTAURA_REDIRECT_URL=${GIFTAURA_REDIRECT_URL:-http://3.108.254.83/api/wallet/payment-callback}

# Background sync for pending add-cash / pay-in
RECHARGE_PAYIN_SYNC_ENABLED=${RECHARGE_PAYIN_SYNC_ENABLED:-true}
RECHARGE_PAYIN_SYNC_CRON=${RECHARGE_PAYIN_SYNC_CRON:-*/10 * * * *}
RECHARGE_PAYIN_SYNC_MIN_AGE_MINUTES=${RECHARGE_PAYIN_SYNC_MIN_AGE_MINUTES:-2}
RECHARGE_PAYIN_SYNC_BATCH_LIMIT=${RECHARGE_PAYIN_SYNC_BATCH_LIMIT:-50}

# GiftAura payout gateway
GIFTAURA_PAYOUT_API_URL=${GIFTAURA_PAYOUT_API_URL:-https://pgapi.giftaura.shop/single_transaction}
GIFTAURA_PAYOUT_REMARK=${GIFTAURA_PAYOUT_REMARK:-Withdrawal}
GIFTAURA_PAYOUT_HISTORY_API_URL=${GIFTAURA_PAYOUT_HISTORY_API_URL:-https://pgapi.giftaura.shop/merchantpayouthistory}
WITHDRAWAL_PAYOUT_SYNC_ENABLED=${WITHDRAWAL_PAYOUT_SYNC_ENABLED:-true}
WITHDRAWAL_PAYOUT_SYNC_CRON=${WITHDRAWAL_PAYOUT_SYNC_CRON:-*/10 * * * *}
WITHDRAWAL_PAYOUT_SYNC_MIN_AGE_MINUTES=${WITHDRAWAL_PAYOUT_SYNC_MIN_AGE_MINUTES:-2}
WITHDRAWAL_PAYOUT_SYNC_BATCH_LIMIT=${WITHDRAWAL_PAYOUT_SYNC_BATCH_LIMIT:-50}
WITHDRAWAL_REQUIRE_APPROVED_KYC=${WITHDRAWAL_REQUIRE_APPROVED_KYC:-true}

# Firebase Cloud Messaging
FIREBASE_SERVICE_ACCOUNT_BASE64=${FIREBASE_SERVICE_ACCOUNT_BASE64:-}
FCM_ANDROID_CHANNEL_ID=${FCM_ANDROID_CHANNEL_ID:-og_rummy_default}

EOF

if [ -n "${REDIS_URL:-}" ]; then
  echo "REDIS_URL configured for deploy"
else
  echo "WARN: REDIS_URL not set — health check will report redis not configured"
fi

docker rm -f "$APP_NAME" >/dev/null 2>&1 || true
docker build -t "$IMAGE_NAME" .
docker run -d \
  --name "$APP_NAME" \
  --restart always \
  -p "$APP_PORT:$CONTAINER_PORT" \
  --env-file .env \
  "$IMAGE_NAME"

attempt=1
while [ "$attempt" -le "$HEALTHCHECK_RETRIES" ]; do
  if curl -fsS "$HEALTHCHECK_URL" >/dev/null 2>&1; then
    echo "Health check passed on attempt $attempt"
    exit 0
  fi

  echo "Health check attempt $attempt failed; waiting ${HEALTHCHECK_INTERVAL}s"
  sleep "$HEALTHCHECK_INTERVAL"
  attempt=$((attempt + 1))
done

echo "Health check failed after ${HEALTHCHECK_RETRIES} attempts" >&2
docker ps -a --filter "name=$APP_NAME" >&2 || true
docker logs --tail 200 "$APP_NAME" >&2 || true
exit 1